Make the tests fail if something gets written to the stderr
To reduces the chances of missing an error.

diff --git a/tests/test_runner b/tests/test_runner
--- a/tests/test_runner
+++ b/tests/test_runner
@@ -51,14 +51,30 @@ else
   run_all_tests
 fi
 
-if $ALL_TESTS_PASSED; then
-  echo -e "\033[32mAll tests passed successfully!\033[0m"
-else
-  echo -e "\033[31mFailed examples:\033[0m"
+print_stderr() {
   while IFS= read -r line; do
     echo "  $line" >&2
   done < "$STDERR_FILE"
+}
+
+# Fail the test if there are errors, but all tests passed
+# Can't set `set -e` everywhere because it would fail the test for soft errors
+# like `grep` not finding a pattern
+if [[ "$ALL_TESTS_PASSED" == true && -s "$STDERR_FILE" ]]; then
+  echo -e "\033[31mAll tests passed, but some errors occurred!\033[0m"
+  print_stderr
   rm "$STDERR_FILE"
 
   exit 1
 fi
+
+# Fail the test if there are failed tests
+if [[ "$ALL_TESTS_PASSED" != true ]]; then
+  echo -e "\033[31mFailed examples:\033[0m"
+  print_stderr
+  rm "$STDERR_FILE"
+
+  exit 1
+fi
+
+echo -e "\033[32mAll tests passed successfully!\033[0m"
